### ISSUE TITLE
Remove Duplicate Source Values

### ISSUE THREAD

**Issue by cannin** [Jigyasa-G/clusterProfiler-JG#12]
Why are there duplicate values? Use a different strategy to allow a user to select a given dataset uniquely.

![dual_strings](https://github.com/Jigyasa-G/clusterProfiler-JG/assets/790284/c1919a90-ada1-4fbd-99c6-ee3feefe134b)

**Comment by Jigyasa-G** [comment]
I have used unique() function for this:
https://github.com/Jigyasa-G/clusterProfiler-JG/blob/ca07e30c88fce56ff3895aec8c1b271ebbed35aa/R/pathwayCommons.R#L70C1-L75C2
